/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playoust_vazquez_mastermind;

import java.util.Random;

/**
 *
 * @author anyavazquez
 */
public class FenetreDeJeu extends javax.swing.JFrame {
    
    
    Joueur player;
    Grille GrilleJeu;
    Pion [] CombiGagnante;
    Pion [] CombiCourante;
    Random generateurAleat = new Random ();
    /**
     * Creates new form FenetreDeJeu
     */
    public FenetreDeJeu() {
        GrilleJeu = new Grille();
        initComponents();
        panneau_choix_pions.setVisible(false);
        
        for (int i=0; i<12; i++) {
            for (int j=0; j<4; j++) {
                PionsGraphique PionGraph = new PionsGraphique(GrilleJeu.PionJeu[i][j]);
                panneau_pions_joueur.add(PionGraph);
            }
        }
        
        for (int i=0; i<12; i++) {
            for (int j=0; j<4; j++) {
                VerifGraphique PetitPion = new VerifGraphique();
                panneau_verif_pions.add(PetitPion);
            }
        }
        
        
        CouleurGraphique color1 = new CouleurGraphique("Jaune");
        panneau_choix_pions.add(color1);
        CouleurGraphique color2 = new CouleurGraphique("Gris");
        panneau_choix_pions.add(color2);
        CouleurGraphique color3 = new CouleurGraphique("Turquoise");
        panneau_choix_pions.add(color3);
        CouleurGraphique color4 = new CouleurGraphique("Rose");
        panneau_choix_pions.add(color4);
        CouleurGraphique color5 = new CouleurGraphique("Vert");
        panneau_choix_pions.add(color5);
        CouleurGraphique color6 = new CouleurGraphique("Bleu");
        panneau_choix_pions.add(color6);
        CouleurGraphique color7 = new CouleurGraphique("Orange");
        panneau_choix_pions.add(color7);
        CouleurGraphique color8 = new CouleurGraphique("Marron");
        panneau_choix_pions.add(color8);
        
        
    }
    public void initialiserPartie(){
        GrilleJeu=new Grille();
        
        for (int i=0; i<4; i++) {
            int choixCouleur = generateurAleat.nextInt(7);
            if (choixCouleur==0) {
                CombiGagnante[i]=new Pion("Rose");
            }
            if (choixCouleur==1) {
                CombiGagnante[i]=new Pion("Jaune");
            }
            if (choixCouleur==2) {
                CombiGagnante[i]=new Pion("Vert");
            }
            if (choixCouleur==3) {
                CombiGagnante[i]=new Pion("Bleu");
            }
            if (choixCouleur==4) {
                CombiGagnante[i]=new Pion("Orange");
            }
            if (choixCouleur==5) {
                CombiGagnante[i]=new Pion("Gris");
            }
            if (choixCouleur==6) {
                CombiGagnante[i]=new Pion("Marron");
            }
            if (choixCouleur==7) {
                CombiGagnante[i]=new Pion("Turquoise");
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_pions_joueur = new javax.swing.JPanel();
        panneau_verif_pions = new javax.swing.JPanel();
        panneau_infos_joueur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_start = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nom_joueur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panneau_choix_pions = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_pions_joueur.setBackground(new java.awt.Color(255, 255, 255));
        panneau_pions_joueur.setLayout(new java.awt.GridLayout(12, 4));
        getContentPane().add(panneau_pions_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 256, 768));

        panneau_verif_pions.setBackground(new java.awt.Color(255, 255, 255));
        panneau_verif_pions.setLayout(new java.awt.GridLayout(24, 2));
        getContentPane().add(panneau_verif_pions, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 128, 768));

        panneau_infos_joueur.setBackground(new java.awt.Color(0, 204, 204));
        panneau_infos_joueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenue dans le Mastermind !");
        panneau_infos_joueur.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        btn_start.setText("J'accepte la mission !");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        panneau_infos_joueur.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Nom du soldat : ");
        panneau_infos_joueur.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        nom_joueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_joueurActionPerformed(evt);
            }
        });
        panneau_infos_joueur.add(nom_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 160, -1));
        panneau_infos_joueur.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 360, -1));

        jLabel4.setText("Le capitaine Barbe-Rousse vous envoie un message, tentez de le déchiffrer !");
        panneau_infos_joueur.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 480, 50));
        panneau_infos_joueur.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 360, -1));

        getContentPane().add(panneau_infos_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 500, 220));

        panneau_choix_pions.setBackground(new java.awt.Color(255, 255, 255));
        panneau_choix_pions.setLayout(new java.awt.GridLayout(4, 2));
        getContentPane().add(panneau_choix_pions, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 500, 530));

        setBounds(0, 0, 1095, 832);
    }// </editor-fold>//GEN-END:initComponents

    private void nom_joueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_joueurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_joueurActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        panneau_choix_pions.setVisible(true);
        initialiserPartie();
        //panneau_pions_joueur.repaint();
        btn_start.setEnabled(false);
    }//GEN-LAST:event_btn_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nom_joueur;
    private javax.swing.JPanel panneau_choix_pions;
    private javax.swing.JPanel panneau_infos_joueur;
    private javax.swing.JPanel panneau_pions_joueur;
    private javax.swing.JPanel panneau_verif_pions;
    // End of variables declaration//GEN-END:variables
}
